services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      # Instalar Chrome y ChromeDriver
      apt-get update && apt-get install -y wget gnupg2
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      apt-get update
      apt-get install -y google-chrome-stable
      CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f3 | cut -d '.' -f1)
      wget https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}
      CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_${CHROME_VERSION})
      wget https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      # Instalar dependencias de Python
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0