services:
  - type: web
    name: flask-speech-to-text
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: OPENAI_API_KEY
        sync: false