services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      # Instalar dependencias del sistema
      apt-get update && apt-get install -y python3-pip ffmpeg
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
      # Configuración adicional para youtube-dl
      mkdir -p $HOME/.config/youtube-dl
      echo "--no-check-certificate" > $HOME/.config/youtube-dl/config
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0