services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      # Instalar ffmpeg y otras dependencias
      apt-get update && apt-get install -y ffmpeg python3-pip
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0