services:
  - type: web
    name: flask-speech-to-text
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      bash -c '
      echo "$GOOGLE_APPLICATION_CREDENTIALS" > google_credentials.json &&
      gunicorn app:app
      '
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12